apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inventory-db
  description: inventory stock service database
  tags:
    - mongod
    - database
spec:
  type: database
  lifecycle: experimental
  owner: group:guests
  system: counter-app